export const SURGERY_ITEMS = [
  "Acido Tranexamico 1000cc",
  "Acido tranexamico 500cc",
  "Adrenalina",
  "Aminofilina",
  "Amiodorona",
  "Amlodipina 10 mg comp.",
  "Amlodipina 5mg comp.",
  "ampicilina 1gr amp",
  "ampicilina sulbactam 1,5 gr amp",
  "Antitetanica amp. Biol (h-1-100)",
  "Aspirinina 100mg comp.",
  "ATB ALTO ESPECTRO",
  "Atracurium 50mg/5ml",
  "Atropina",
  "Bupivacaina 5mg / ml x 20 ml",
  "Caja de paro",
  "Cefalexina 500 comp",
  "Cefalotina",
  "Cefazolina",
  "Cinta reactiva",
  "ciprofloxacina 400mg amp",
  "Clindamicina",
  "Clindamicina comp. 300mg",
  "Clonazepan,5mg",
  "Clonhidina 150mg /1 ml",
  "Cloruro de potasio",
  "Cloruro de sodio",
  "Dexamentasona",
  "Diazepan 10mg amp.",
  "Diclofenac",
  "Diclofenac + beta B12 comp",
  "Diclofenac c/p 50mg com",
  "Diclofenac comp. 75mg",
  "Difenidramina",
  "Digoxina",
  "Dipirona",
  "Dopamina",
  "Duracaina Hiperbarica C/A",
  "Enalapril",
  "enalpril 10 mg",
  "Enoxaparine 0,4mg",
  "Etilefrina",
  "Expansor plastico (revertidor de bloq. )",
  "Fentanilo",
  "Flumazenil 5ml",
  "Furosemida",
  "gentamicina 80mg amp",
  "Gluconato de calcio",
  "Heparina Sodica",
  "Hidrocortisona",
  "Ibuprofeno comp x400mg comp.",
  "Insulina Corriente (humana)",
  "Jeringa Insulina 1cc s/a",
  "Ketamina",
  "Ketorolac",
  "Ketorolac comp subl. 10mg",
  "Labetelolol",
  "Lidocaina 20mg / ml",
  "Lorazepan subl. 1mg",
  "MEDIC. ENFERMERIA",
  "Metoclopramida (reliveran)",
  "Midazolan",
  "Morfina",
  "Nabulfina",
  "Naloxona",
  "Neostigmina",
  "Nitroglicerina",
  "nitroprusiato",
  "noraadrenalina",
  "Omeprazol 20mg comp.",
  "omeprazol frasco amp. x 40 mg",
  "Ondansetron",
  "Paracetamol 500mg",
  "Piperazilina",
  "Propofol",
  "Ranitidina",
  "Remifentanilo",
  "Rifampicina 600mg amp",
  "Ringer lactato",
  "Sevorane 250ml",
  "Solucion glucosada",
  "Solucion molar bicarbonato",
  "Solucion molar potasio",
  "Solucion oftalmologica esteril",
  "Succinicolina /100 mg",
  "Succinicolina/ 500mg fco",
  "Succinicolina/ 50mg",
  "Tramadol comp. 50mg",
  "Tramadol/ 50ml",
  "Tramadol/1000ml",
  "Vancomicina",
  "Vecuronio",
  "Voluven",
  "Xilocayna 2% 5ml",
  "Xilocayna c/e 20 ml( lidocaina)",
  "Xilocayna jalea 25mg"
];
