
    INSERT INTO quirofano.catalog_items (name, category, active)
    VALUES 
    ('Acido  tranexamico 500cc', 'surgery', true),
    ('Acido Tranexamico 1000cc', 'surgery', true),
    ('Atropina', 'surgery', true),
    ('Cefalotina', 'surgery', true),
    ('Cefazolina', 'surgery', true),
    ('Dexamentasona', 'surgery', true),
    ('Diclofenac', 'surgery', true),
    ('Dipirona', 'surgery', true),
    ('Duracaina Hiperbarica C/A', 'surgery', true),
    ('Etilefrina', 'surgery', true),
    ('Fentanilo', 'surgery', true),
    ('Flumazenil 5ml', 'surgery', true),
    ('Voluven', 'surgery', true),
    ('Ringer lactato', 'surgery', true),
    ('Hidrocortisona', 'surgery', true),
    ('Ketamina', 'surgery', true),
    ('Ketorolac', 'surgery', true),
    ('Metoclopramida (reliveran)', 'surgery', true),
    ('Midazolan', 'surgery', true),
    ('Morfina', 'surgery', true),
    ('Nabulfina', 'surgery', true),
    ('Naloxona', 'surgery', true),
    ('Neostigmina', 'surgery', true),
    ('Ranitidina', 'surgery', true),
    ('Remifentanilo', 'surgery', true),
    ('Sevorane 250ml', 'surgery', true),
    ('Succinicolina /100 mg', 'surgery', true),
    ('Succinicolina/ 50mg', 'surgery', true),
    ('Succinicolina/ 500mg fco', 'surgery', true),
    ('Tramadol/ 50ml', 'surgery', true),
    ('Tramadol/1000ml', 'surgery', true),
    ('Vancomicina', 'surgery', true),
    ('Vecuronio', 'surgery', true),
    ('Xilocayna 2% 5ml', 'surgery', true),
    ('Xilocayna c/e 20 ml( lidocaina)', 'surgery', true),
    ('Bupivacaina 5mg / ml x 20 ml', 'surgery', true),
    ('Lidocaina 20mg / ml', 'surgery', true),
    ('Propofol', 'surgery', true),
    ('Solucion oftalmologica esteril', 'surgery', true),
    ('Clindamicina', 'surgery', true),
    ('Xilocayna jalea 25mg', 'surgery', true),
    ('Clonhidina 150mg /1 ml', 'surgery', true),
    ('Caja de paro', 'surgery', true),
    ('Enalapril', 'surgery', true),
    ('Difenidramina', 'surgery', true),
    ('Furosemida', 'surgery', true),
    ('Adrenalina', 'surgery', true),
    ('Labetelolol', 'surgery', true),
    ('Amiodorona', 'surgery', true),
    ('Digoxina', 'surgery', true),
    ('Heparina Sodica', 'surgery', true),
    ('Solucion glucosada', 'surgery', true),
    ('noraadrenalina', 'surgery', true),
    ('Gluconato de calcio', 'surgery', true),
    ('Nitroglicerina', 'surgery', true),
    ('Cloruro de potasio', 'surgery', true),
    ('Dopamina', 'surgery', true),
    ('Cloruro de sodio', 'surgery', true),
    ('Solucion molar potasio', 'surgery', true),
    ('Solucion molar bicarbonato', 'surgery', true),
    ('nitroprusiato', 'surgery', true),
    ('Aminofilina', 'surgery', true),
    ('Atracurium 50mg/5ml', 'surgery', true),
    ('Ondansetron', 'surgery', true),
    ('MEDIC. ENFERMERIA', 'surgery', true),
    ('Diclofenac comp. 75mg', 'surgery', true),
    ('Ketorolac comp subl. 10mg', 'surgery', true),
    ('Aspirinina 100mg comp.', 'surgery', true),
    ('Paracetamol 500mg', 'surgery', true),
    ('Ibuprofeno comp x400mg comp.', 'surgery', true),
    ('Antitetanica amp. Biol (h-1-100)', 'surgery', true),
    ('Cefalexina 500 comp', 'surgery', true),
    ('Amlodipina 5mg comp.', 'surgery', true),
    ('Amlodipina 10 mg comp.', 'surgery', true),
    ('enalpril 10 mg', 'surgery', true),
    ('Clonazepan,5mg', 'surgery', true),
    ('Lorazepan subl. 1mg', 'surgery', true),
    ('omeprazol frasco amp. x 40 mg', 'surgery', true),
    ('Omeprazol 20mg comp.', 'surgery', true),
    ('Enoxaparine 0,4mg', 'surgery', true),
    ('Cinta reactiva', 'surgery', true),
    ('Diazepan 10mg amp.', 'surgery', true),
    ('Jeringa Insulina 1cc s/a', 'surgery', true),
    ('Insulina Corriente (humana)', 'surgery', true),
    ('Clindamicina comp. 300mg', 'surgery', true),
    ('Tramadol comp. 50mg', 'surgery', true),
    ('Diclofenac c/p 50mg com', 'surgery', true),
    ('Diclofenac + beta B12 comp', 'surgery', true),
    ('ATB  ALTO ESPECTRO', 'surgery', true),
    ('Piperazilina', 'surgery', true),
    ('ampicilina 1gr amp', 'surgery', true),
    ('gentamicina 80mg amp', 'surgery', true),
    ('ciprofloxacina 400mg  amp', 'surgery', true),
    ('ampicilina sulbactam 1,5 gr amp', 'surgery', true),
    ('Rifampicina 600mg amp', 'surgery', true),
    ('Expansor plastico (revertidor de bloq. )', 'surgery', true)
    ON CONFLICT (name) DO NOTHING;
    