-- Create Catalog Items table
CREATE TABLE IF NOT EXISTS quirofano.catalog_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT DEFAULT 'surgery', -- surgery, anesthesia, etc.
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE quirofano.catalog_items ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read for authenticated users" ON quirofano.catalog_items
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable write for authenticated users" ON quirofano.catalog_items
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert initial items
INSERT INTO quirofano.catalog_items (name, category) VALUES
('Acido Tranexamico 1000cc', 'surgery'),
('Acido tranexamico 500cc', 'surgery'),
('Adrenalina', 'anesthesia'),
('Aminofilina', 'anesthesia'),
('Amiodorona', 'anesthesia'),
('Amlodipina 10 mg comp.', 'surgery'),
('Amlodipina 5mg comp.', 'surgery'),
('ampicilina 1gr amp', 'surgery'),
('ampicilina sulbactam 1,5 gr amp', 'surgery'),
('Antitetanica amp. Biol (h-1-100)', 'surgery'),
('Aspirinina 100mg comp.', 'surgery'),
('ATB ALTO ESPECTRO', 'surgery'),
('Atracurium 50mg/5ml', 'anesthesia'),
('Atropina', 'anesthesia'),
('Bupivacaina 5mg / ml x 20 ml', 'anesthesia'),
('Caja de paro', 'surgery'),
('Cefalexina 500 comp', 'surgery'),
('Cefalotina', 'surgery'),
('Cefazolina', 'surgery'),
('Cinta reactiva', 'surgery'),
('ciprofloxacina 400mg amp', 'surgery'),
('Clindamicina', 'surgery'),
('Clindamicina comp. 300mg', 'surgery'),
('Clonazepan,5mg', 'surgery'),
('Clonhidina 150mg /1 ml', 'anesthesia'),
('Cloruro de potasio', 'anesthesia'),
('Cloruro de sodio', 'surgery'),
('Dexamentasona', 'anesthesia'),
('Diazepan 10mg amp.', 'anesthesia'),
('Diclofenac', 'surgery'),
('Diclofenac + beta B12 comp', 'surgery'),
('Diclofenac c/p 50mg com', 'surgery'),
('Diclofenac comp. 75mg', 'surgery'),
('Difenidramina', 'anesthesia'),
('Digoxina', 'anesthesia'),
('Dipirona', 'surgery'),
('Dopamina', 'anesthesia'),
('Duracaina Hiperbarica C/A', 'anesthesia'),
('Enalapril', 'surgery'),
('enalpril 10 mg', 'surgery'),
('Enoxaparine 0,4mg', 'surgery'),
('Etilefrina', 'anesthesia'),
('Expansor plastico (revertidor de bloq. )', 'anesthesia'),
('Fentanilo', 'anesthesia'),
('Flumazenil 5ml', 'anesthesia'),
('Furosemida', 'anesthesia'),
('gentamicina 80mg amp', 'surgery'),
('Gluconato de calcio', 'anesthesia'),
('Heparina Sodica', 'surgery'),
('Hidrocortisona', 'anesthesia'),
('Ibuprofeno comp x400mg comp.', 'surgery'),
('Insulina Corriente (humana)', 'surgery'),
('Jeringa Insulina 1cc s/a', 'surgery'),
('Ketamina', 'anesthesia'),
('Ketorolac', 'surgery'),
('Ketorolac comp subl. 10mg', 'surgery'),
('Labetelolol', 'anesthesia'),
('Lidocaina 20mg / ml', 'anesthesia'),
('Lorazepan subl. 1mg', 'surgery'),
('MEDIC. ENFERMERIA', 'surgery'),
('Metoclopramida (reliveran)', 'surgery'),
('Midazolan', 'anesthesia'),
('Morfina', 'anesthesia'),
('Nabulfina', 'anesthesia'),
('Naloxona', 'anesthesia'),
('Neostigmina', 'anesthesia'),
('Nitroglicerina', 'anesthesia'),
('nitroprusiato', 'anesthesia'),
('noraadrenalina', 'anesthesia'),
('Omeprazol 20mg comp.', 'surgery'),
('omeprazol frasco amp. x 40 mg', 'surgery'),
('Ondansetron', 'anesthesia'),
('Paracetamol 500mg', 'surgery'),
('Piperazilina', 'surgery'),
('Propofol', 'anesthesia'),
('Ranitidina', 'surgery'),
('Remifentanilo', 'anesthesia'),
('Rifampicina 600mg amp', 'surgery'),
('Ringer lactato', 'surgery'),
('Sevorane 250ml', 'anesthesia'),
('Solucion glucosada', 'surgery'),
('Solucion molar bicarbonato', 'anesthesia'),
('Solucion molar potasio', 'anesthesia'),
('Solucion oftalmologica esteril', 'surgery'),
('Succinicolina /100 mg', 'anesthesia'),
('Succinicolina/ 500mg fco', 'anesthesia'),
('Succinicolina/ 50mg', 'anesthesia'),
('Tramadol comp. 50mg', 'surgery'),
('Tramadol/ 50ml', 'surgery'),
('Tramadol/1000ml', 'surgery'),
('Vancomicina', 'surgery'),
('Vecuronio', 'anesthesia'),
('Voluven', 'surgery'),
('Xilocayna 2% 5ml', 'anesthesia'),
('Xilocayna c/e 20 ml( lidocaina)', 'anesthesia'),
('Xilocayna jalea 25mg', 'anesthesia'),
('ampicilina 1gr amp', 'surgery'),
('ampicilina sulbactam 1,5 gr amp', 'surgery'),
('ciprofloxacina 400mg  amp', 'surgery'),
('enalpril 10 mg', 'surgery'),
('gentamicina 80mg amp', 'surgery'),
('nitroprusiato', 'anesthesia'),
('noraadrenalina', 'anesthesia'),
('omeprazol frasco amp. x 40 mg', 'surgery')
ON CONFLICT (name) DO NOTHING;
